---
- name: Debug message
  ansible.builtin.debug:
    msg: "Create task to install and preparing DB server"

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    update_cache: yes

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Get path of PostgreSQL configuration file
  ansible.builtin.command:
    cmd: sudo -u postgres psql -t -P format=unaligned -c 'SHOW hba_file;'
  register: hba_file

- name: Create a new user
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
  become_user: postgres

- name: Create database
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become_user: postgres

- name: Set PostgreSQL to listen on all interfaces
  community.postgresql.postgresql_alter_system:
    parameter: listen_addresses
    value: '*'
  become_user: postgres
  notify:
    - Restart PostgreSQL

- name: Grant user access to the database using peer authentication
  community.postgresql.postgresql_pg_hba:
    dest: "{{ hba_file.stdout }}"
    contype: host
    users: "{{ db_user }}"
    source: all
    database: "{{ db_name }}"
    method: scram-sha-256
    create: true
  become_user: postgres
  notify:
    - Restart PostgreSQL
